export const Users = [
  {
    id:1,
    profilePicture: "assets/person/2.jpeg",
    username: "John Doe",
  },
  {
    id:2,
    profilePicture: "assets/person/3.jpeg",
    username: "Jane Smith",
  },
  {
    id:3,
    profilePicture: "assets/person/7.jpeg",
    username: "Mike Johnson",
  },
  {
    id:4,
    profilePicture: "assets/person/1.jpeg",
    username: "Sarah Lee",
  },
  {
    id:5,
    profilePicture: "assets/person/6.jpeg",
    username: "David Kim",
  },
  {
    id:6,
    profilePicture: "assets/person/4.jpeg",
    username: "Emily Wong",
  },
  {
    id:7,
    profilePicture: "assets/person/11.jpeg",
    username: "Mark Chen",
  },
  {
    id:8,
    profilePicture: "assets/person/5.jpeg",
    username: "Lisa Chang",
  },
  {
    id:9,
    profilePicture: "assets/person/12.jpeg",
    username: "Kevin Nguyen",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "Rachel Park",
  },
  {
    id:11,
    profilePicture: "assets/person/9.jpeg",
    username: "Emma Johnson",
  },
  {
    id:12,
    profilePicture: "assets/person/13.jpeg",
    username: "William Chen",
  },
  {
    id:13,
    profilePicture: "assets/person/8.jpeg",
    username: "Sophia Patel",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Beautiful sunset at the beach",
    photo: "assets/post/1.jpeg",
    date: "Nov 5, 2022",
    userId: 4,
    like: 32,
    comment: 1,
    album: "Random",
    tags: "beach sun"
  },
  {
    id: 2,
    desc: "Family Vacation!",
    photo: "assets/post/2.jpeg",
    date: "Jan 6, 2023",
    userId: 6,
    like: 2,
    comment: 1,
    album: "Family",
    tags: "family city",
  },
  {
    id: 3,
    desc: "My new puppy",
    photo: "assets/post/3.jpeg",
    date: "Mar 9, 2023",
    userId: 7,
    like: 61,
    comment: 1,
    album: "Dogs",
  },
  {
    id: 4,
    desc: "Winter Wonderland",
    photo: "assets/post/4.jpeg",
    date: "Dec 26, 2022",
    userId: 5,
    like: 7,
    comment: 1,
    album: "Christmas",
    tags: "snow",
  },
  {
    id: 5,
    desc: "Throwback Thursday",
    photo: "assets/post/5.jpeg",
    date: "Nov 5, 2022",
    userId: 4,
    like: 23,
    comment: 1,
    album: "Random",
  },
  {
    id: 6,
    desc: "Exploring the City",
    photo: "assets/post/6.jpeg",
    date: "Nov 5, 2022",
    userId: 4,
    like: 44,
    comment: 1,
    album: "Random",
    tags: "sun",
  },
  {
    id: 7,
    desc: "Hiking",
    photo: "assets/post/7.jpeg",
    date: "Feb 28, 2023",
    userId: 5,
    like: 52,
    comment: 1,
    album: "February",
  },
  {
    id: 8,
    desc: "Birthday Wishes",
    photo: "assets/post/8.jpeg",
    date: "May 25, 2022",
    userId: 1,
    like: 15,
    comment: 2,
    album: "Birthdays",
  },
  {
    id: 9,
    desc: "Visiting the Grand Canyon",
    photo: "assets/post/9.jpeg",
    date: "Nov 27, 2022",
    userId: 9,
    like: 11,
    comment: 2,
    album: "Thankful",
    tags: "sun",
  },
  {
    id: 10,
    desc: "Watching the Fireworks",
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: 2,
    like: 104,
    comment: 2,
    album: "New Years!",
    tags: "celebration",
  },
  {
    id: 11,
    desc: "Bunnies and Family",
    photo: "assets/post/11.jpeg",
    date: "Apr 10, 2023",
    userId: 11,
    like: 104,
    comment: 1,
    album: "Easter",
    tags: "bunny",
  },
  {
    id: 12,
    desc: "Sand Volleyball in California",
    photo: "assets/post/12.jpeg",
    date: "Mar 25, 2023",
    userId: 12,
    like: 104,
    comment: 1,
    album: "Spring Break",
    tags: "sand",
  },
  {
    id: 13,
    desc: "Finally 21",
    photo: "assets/post/13.jpeg",
    date: "Apr 23, 2023",
    userId: 13,
    like: 104,
    comment: 1,
    album: "My Birthday",
    tags: "drinks",
  },
];
